# Generated by Django 4.2.3 on 2023-07-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='book_name',
        ),
    ]
