# Generated by Django 4.2.3 on 2023-08-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rest_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_model_1', models.CharField(max_length=100)),
                ('rest_model_2', models.TextField()),
            ],
        ),
    ]
