# Generated by Django 4.2.3 on 2023-08-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_frame', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rest_api',
            new_name='rest_api_function',
        ),
    ]
