# Generated by Django 4.2.3 on 2023-08-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_frame', '0002_rename_rest_api_rest_api_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest_api_function',
            name='rest_model_2',
            field=models.IntegerField(),
        ),
    ]
