# Generated by Django 4.2.3 on 2023-08-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_frame', '0003_alter_rest_api_function_rest_model_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest_api_function',
            name='rest_model_2',
            field=models.TextField(),
        ),
    ]
