# Generated by Django 4.2.3 on 2023-07-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kamadiya', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='price',
        ),
    ]
