# Generated by Django 4.2.3 on 2023-07-20 07:50

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamadiya', '0004_book_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_title', models.CharField(max_length=100)),
                ('blog_content', models.TextField(max_length=10000)),
                ('author_name', models.CharField(max_length=100)),
                ('date_of_publication', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='content', unique=True),
        ),
    ]
