# Generated by Django 4.2.3 on 2023-07-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamadiya', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='free',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(max_length=100)),
                ('img', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
