# Generated by Django 4.2.3 on 2023-07-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamadiya', '0007_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free',
            name='img',
            field=models.FileField(default=None, upload_to='uploads/'),
        ),
    ]
