# Generated by Django 4.2.3 on 2023-07-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kamadiya', '0008_alter_free_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free',
            name='img',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
